# Generated by Django 5.0.2 on 2024-03-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_art_link', models.URLField(max_length=400)),
                ('preview_sound', models.URLField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songs', models.ManyToManyField(blank=True, related_name='songs_in_playlist', to='FitBeatsApp.song')),
            ],
        ),
    ]
