# Generated by Django 5.0.2 on 2024-03-24 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entire_Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intensity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exerciser', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.URLField(max_length=400)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_art_link', models.URLField(max_length=400)),
                ('preview_sound', models.URLField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=200)),
                ('entire_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitBeatsApp.entire_workout')),
            ],
        ),
        migrations.AddField(
            model_name='entire_workout',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FitBeatsApp.playlist'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='songs_in_playlist', to='FitBeatsApp.song'),
        ),
    ]
