# Generated by Django 5.0.2 on 2024-03-24 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitBeatsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='cover_image',
            field=models.URLField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Workout_Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(max_length=200)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intensity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exercise_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitBeatsApp.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Entire_Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitBeatsApp.playlist')),
                ('segments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitBeatsApp.workout_segment')),
            ],
        ),
    ]
