<<<<<<< HEAD:FitBeats/FitBeatsApp/migrations/0002_entire_workout_playlist_cover_image_playlist_name_and_more.py
# Generated by Django 4.1.6 on 2024-03-24 09:11
=======
# Generated by Django 5.0.2 on 2024-03-24 07:25
>>>>>>> db38d6670539b2ed95f3e54b082232aab002c794:FitBeats/FitBeatsApp/migrations/0002_playlist_cover_image_playlist_name_entire_workout_and_more.py

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitBeatsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entire_Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intensity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='cover_image',
            field=models.URLField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
<<<<<<< HEAD:FitBeats/FitBeatsApp/migrations/0002_entire_workout_playlist_cover_image_playlist_name_and_more.py
=======
            name='Entire_Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intensity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exerciser', models.CharField(max_length=20)),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FitBeatsApp.playlist')),
            ],
        ),
        migrations.CreateModel(
>>>>>>> db38d6670539b2ed95f3e54b082232aab002c794:FitBeats/FitBeatsApp/migrations/0002_playlist_cover_image_playlist_name_entire_workout_and_more.py
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=200)),
                ('entire_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitBeatsApp.entire_workout')),
            ],
        ),
        migrations.AddField(
            model_name='entire_workout',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FitBeatsApp.playlist'),
        ),
    ]
