# Generated by Django 5.0.2 on 2024-03-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitBeatsApp', '0002_exercise_playlist_cover_image_playlist_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout_segment',
            name='exercise_names',
        ),
        migrations.AddField(
            model_name='workout_segment',
            name='exercise_names',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='FitBeatsApp.exercise'),
        ),
    ]
