# Generated by Django 5.0.2 on 2024-03-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitBeatsApp', '0005_alter_entire_workout_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='entire_workout',
            name='duration',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entire_workout',
            name='intensity',
            field=models.DecimalField(decimal_places=2, default=' ', max_digits=10),
            preserve_default=False,
        ),
    ]
